package-lock.json
package.json
src/components/Landing/BackgroundVideo.js
src/components/Landing/Banner.js
src/components/Landing/Input.js
src/components/Landing/Main.js
src/components/Landing/Navbar.js
src/components/Landing/Typing.js
src/components/Landing/index.js
src/index.html

Updates:
1) Landing page design complete
Problems:
1) Navbar is not working yet (i.e. profile, and hamburger)
2) Submit on Form is not connected yet
Jacky's to-do next
1) Make Form submit working

landingPageFirstUpdate

---

src/components/WordCloud/Loading.js
src/components/WordCloud/WordcloudFullScreen.js
src/components/WordCloud/index.js

update the wordcloud component UI

Word cloud2

---

.gitignore
server/api/tweets.js
src/components/Common/Input.js
src/components/Landing/Main.js
src/components/WordCloud/Loading.js
src/components/WordCloud/index.js

updated the loading component and refactored some front end components 
.gitignore now has dist instead of dist/main.js

Word cloud3

---

src/components/Common/Message.js
src/components/Navbar/index.js
src/components/WordCloud/index.js

Update
1. added message component to handle data fetching failure and not providing searchTerm scenarios
Todo next
1. add this feature: search bar stores the searchTerm after searching

minor UI improvement to wordcloud

---

src/components/App.js
src/components/EmbeddedTweets.js
src/components/WordCloud/index.js

Updates:
1) Clicking words will display tweets
Todo:
1) UI of Tweet Display

Connected tweets

---

src/components/WordCloud/index.js

Update:
1) Keep wordcloud and tweets side by side
Jacky's to-do next:
1) Each search should clean up the list arrays in redux store, removing the tweets displayed from the previous search
2) Search should show up on link and in search bar
Issue found:
1) Searching the same term more than once lead to duplicate tweets

Tweets ui improved

---

package-lock.json
server/api/tweets.js
server/db/Tweet.js
server/twitter/fetchTweets.js
server/twitter/parseTweets.js
src/components/EmbeddedTweets.js
src/components/WordCloud/WordCloudComponent.js

- update Tweet model to include additional information about the tweet
- update the fetch and parse methods to pass tweet info in the ids array in word freq objects

Enable id sorting

---

src/components/EmbeddedTweets.js
src/helperFunctions.js

- Add functionality to sort tweetData array by any key in tweetData objects

Sort tweets

---

src/components/EmbeddedTweets.js

added reply and retweet functionality for loggedin user

added reply and retweet functionality for loggedin user

---

src/components/WordCloud/index.js
src/components/WordCloud/oldIndex.js

layout redo is only partly done

layout is partly updated

---

src/components/Common/Input.js
src/reducers/tweetsReducer.js
src/reducers/wordcloudReducer.js

Wordcloud and tweets in redux store gets reset when user searches

wordcloud and tweets reset everytime user searches

---

server/twitter/fetchTweets.js
server/twitter/parseTweets.js

- update the query for twitter API to remove retweets

Destroy dups

---

src/components/EmbeddedTweets.js
src/components/WordCloud/WordCloudComponent.js
src/components/WordCloud/index.js
src/components/theme.js

some more updated to the layout of the cloud page. also made the font on the cloud bigger.
couldn't figure out a way to change the page background color other then by changing the theme background default color. Have to see if there is a better way.

Cloud layout

---

src/components/Landing/Main.js
src/components/Navbar/Search.js
src/components/Navbar/index.js
src/components/WordCloud/WordCloudComponent.js
src/components/WordCloud/index.js
src/index.html

Search has been moved to the navbar

Search navbar

---

server/api/index.js
server/api/tweet.js
server/twitter/fetchTweets.js
server/twitter/replyToTweet.js
server/twitter/twitterSetup.js
src/components/WordCloud/WordCloudComponent.js
src/components/WordCloud/index.js

Updates:
1) Refactored server/twitter slightly by taking the twitter client API object instantiation from parseTweet.js to twitterSetup.js
2) started the backend setup (Twit API and our endpoint) for responding to Tweets
To-do next:
1) Front-end input bar for typing and respond back

untested, first commit for tweet response functionality (backend)

---

src/components/WordCloud/WordCloudComponent.js
src/components/WordCloud/WordPopover.js
src/reducers/wordElementReducer.js

show tweets button in popover on the word cloud is working

show tweets working

---

server/api/tweet.js
server/twitter/replyToTweet.js
src/components/EmbeddedTweets.js
src/components/TweetInfo.js
src/components/TweetResponder.js

Pressing Enter in text bar to individual tweet will respond to the corresponding tweet

Respond to tweet

---

src/components/WordCloud/WordPopover.js
src/reducers/wordcloudReducer.js

remove word from the cloud working

remove word working

---

src/components/WordCloud/WordPopover.js

WordPopover add to search will update the route now

WordPopover add to search will update the route now

---

src/reducers/index.js
src/reducers/lineChartReducer.js

added reducer for the line chart

created lineChart Reducer

---

server/api/tweets.js
src/components/Navbar/Search.js
src/reducers/lineChartReducer.js

- adding routes to search, so all data i fetched when the user searches

Time dependent fetch

---

src/components/Navbar/Search.js
src/components/Search/index.js
src/reducers/thunks.js

Refactor. Added searchRequest thunk. Eliminated duplicate code and axios calls from Search component and index.js in Search

added searchRequest thunk

---

package-lock.json
package.json
src/components/LineChart/index.js

added the time-scale chart; data not loaded yet
issues:
1) no longer independent page
2) line-chart data currently not loaded to the redux store

added the time-scale chart; data not loaded yet

---

src/components/Search/WordPopover.js
src/reducers/thunks.js

Fixed a couple of bugs. 
The removed words get cleared now when there is a new search request.
Add to search had stopped working in the popover component.  Fixed the bug

Bug fix alex

---

server/api/tweets.js
src/components/BarChart/index.js
src/components/BarChart/utils.js
src/components/LineChartTime/index.js
src/components/LineChartTime/utils.js

Only showing the top 10 word on the LineChart.  Refactored BarChart (moved helper functions to utils.js)

top 10 word showing on the line chart.  refactored BarChart

---

src/components/Waffle/index.js

changed waffle color

---

src/components/BarChart/index.js
src/components/LineChartTime/index.js
src/components/Waffle/index.js

Text color is now white.  and the font is a little bigger

updated text color on the charts

---

src/components/Waffle/index.js

fix Waffle clicking on empty square undefined error

fix Waffle clicking on empty square

---

src/components/Navbar/Search.js
src/components/Search/index.js
src/reducers/thunks.js

line chart working on hard reload

refactor so lineChart works on hard reload
